name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    -  name: printing first name
       run: echo "Sunil"
    -  name: printing last name
       run: echo "Aldar"
    
